// ============================================
// KHIMI DELICIAS - PRODUTOS
// ============================================
// Arquivo separado com todos os produtos
// Facilmente editável pela dona (Khimi)
// ============================================

const PRODUTOS = [
  // ============================================
  // BOLOS (50 produtos)
  // ============================================
  {
    id: "bolo1",
    slug: "bolo-chocolate-cremoso",
    categoria: "bolos",
    nome_pt: "Bolo de Chocolate Cremoso",
    nome_en: "Creamy Chocolate Cake",
    preco: "350 MT",
    descricao_pt: "Bolo fofinho de chocolate com cobertura cremosa e granulados. Perfeito para qualquer ocasião.",
    descricao_en: "Soft chocolate cake with creamy topping and sprinkles. Perfect for any occasion.",
    imagens: ["images/bolos/bolo1.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Chocolate", "Chocolate Branco"]
  },
  {
    id: "bolo2",
    slug: "bolo-morango-fresco",
    categoria: "bolos",
    nome_pt: "Bolo de Morango Fresco",
    nome_en: "Fresh Strawberry Cake",
    preco: "400 MT",
    descricao_pt: "Delicioso bolo de baunilha com camadas de morango fresco e chantilly.",
    descricao_en: "Delicious vanilla cake with fresh strawberry layers and whipped cream.",
    imagens: ["images/bolos/bolo2.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Baunilha", "Morango"]
  },
  {
    id: "bolo3",
    slug: "bolo-red-velvet",
    categoria: "bolos",
    nome_pt: "Bolo Red Velvet",
    nome_en: "Red Velvet Cake",
    preco: "450 MT",
    descricao_pt: "Clássico bolo red velvet com cream cheese frosting. Elegante e delicioso.",
    descricao_en: "Classic red velvet cake with cream cheese frosting. Elegant and delicious.",
    imagens: ["images/bolos/bolo3.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Red Velvet"]
  },
  {
    id: "bolo4",
    slug: "bolo-coco-cremoso",
    categoria: "bolos",
    nome_pt: "Bolo de Coco Cremoso",
    nome_en: "Creamy Coconut Cake",
    preco: "320 MT",
    descricao_pt: "Bolo macio de coco com cobertura de leite condensado e coco ralado.",
    descricao_en: "Soft coconut cake with condensed milk topping and grated coconut.",
    imagens: ["images/bolos/bolo4.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Coco"]
  },
  {
    id: "bolo5",
    slug: "bolo-cenoura-chocolate",
    categoria: "bolos",
    nome_pt: "Bolo de Cenoura com Chocolate",
    nome_en: "Carrot Cake with Chocolate",
    preco: "300 MT",
    descricao_pt: "Tradicional bolo de cenoura com cobertura de chocolate meio amargo.",
    descricao_en: "Traditional carrot cake with semi-sweet chocolate topping.",
    imagens: ["images/bolos/bolo5.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Cenoura"]
  },
  {
    id: "bolo6",
    slug: "bolo-limao-siciliano",
    categoria: "bolos",
    nome_pt: "Bolo de Limão Siciliano",
    nome_en: "Sicilian Lemon Cake",
    preco: "380 MT",
    descricao_pt: "Bolo refrescante de limão siciliano com glacê de limão.",
    descricao_en: "Refreshing Sicilian lemon cake with lemon glaze.",
    imagens: ["images/bolos/bolo6.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Limão"]
  },
  {
    id: "bolo7",
    slug: "bolo-marmore",
    categoria: "bolos",
    nome_pt: "Bolo Mármore",
    nome_en: "Marble Cake",
    preco: "330 MT",
    descricao_pt: "Bolo mesclado de baunilha e chocolate com textura única.",
    descricao_en: "Marbled vanilla and chocolate cake with unique texture.",
    imagens: ["images/bolos/bolo7.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Mármore"]
  },
  {
    id: "bolo8",
    slug: "bolo-nozes-caramelo",
    categoria: "bolos",
    nome_pt: "Bolo de Nozes com Caramelo",
    nome_en: "Walnut Caramel Cake",
    preco: "480 MT",
    descricao_pt: "Bolo de nozes com cobertura de caramelo salgado e pedaços de nozes.",
    descricao_en: "Walnut cake with salted caramel topping and walnut pieces.",
    imagens: ["images/bolos/bolo8.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Nozes"]
  },
  {
    id: "bolo9",
    slug: "bolo-prestigio",
    categoria: "bolos",
    nome_pt: "Bolo Prestígio",
    nome_en: "Prestige Cake",
    preco: "370 MT",
    descricao_pt: "Bolo de chocolate recheado com coco e leite condensado. Sabor irresistível!",
    descricao_en: "Chocolate cake filled with coconut and condensed milk. Irresistible flavor!",
    imagens: ["images/bolos/bolo9.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Prestígio"]
  },
  {
    id: "bolo10",
    slug: "bolo-abacaxi-coco",
    categoria: "bolos",
    nome_pt: "Bolo de Abacaxi com Coco",
    nome_en: "Pineapple Coconut Cake",
    preco: "360 MT",
    descricao_pt: "Bolo de abacaxi caramelizado com cobertura de coco. Tropical e delicioso.",
    descricao_en: "Caramelized pineapple cake with coconut topping. Tropical and delicious.",
    imagens: ["images/bolos/bolo10.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Abacaxi"]
  },
  {
    id: "bolo11",
    slug: "bolo-ninho-morango",
    categoria: "bolos",
    nome_pt: "Bolo de Ninho com Morango",
    nome_en: "Nest Milk Strawberry Cake",
    preco: "420 MT",
    descricao_pt: "Bolo de leite ninho com recheio de morango fresco e chantilly.",
    descricao_en: "Nest milk cake with fresh strawberry filling and whipped cream.",
    imagens: ["images/bolos/bolo11.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Ninho", "Morango"]
  },
  {
    id: "bolo12",
    slug: "bolo-cafe-chocolate",
    categoria: "bolos",
    nome_pt: "Bolo de Café com Chocolate",
    nome_en: "Coffee Chocolate Cake",
    preco: "390 MT",
    descricao_pt: "Bolo de café intenso com ganache de chocolate. Para amantes de café!",
    descricao_en: "Intense coffee cake with chocolate ganache. For coffee lovers!",
    imagens: ["images/bolos/bolo12.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Café", "Chocolate"]
  },
  {
    id: "bolo13",
    slug: "bolo-churros",
    categoria: "bolos",
    nome_pt: "Bolo de Churros",
    nome_en: "Churros Cake",
    preco: "340 MT",
    descricao_pt: "Bolo com sabor de churros, cobertura de doce de leite e canela.",
    descricao_en: "Cake with churros flavor, dulce de leche topping and cinnamon.",
    imagens: ["images/bolos/bolo13.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Churros"]
  },
  {
    id: "bolo14",
    slug: "bolo-paçoca",
    categoria: "bolos",
    nome_pt: "Bolo de Paçoca",
    nome_en: "Peanut Cake",
    preco: "310 MT",
    descricao_pt: "Bolo de amendoim com cobertura de paçoca triturada. Sabor brasileiro!",
    descricao_en: "Peanut cake with crushed paçoca topping. Brazilian flavor!",
    imagens: ["images/bolos/bolo14.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Paçoca"]
  },
  {
    id: "bolo15",
    slug: "bolo-oreo",
    categoria: "bolos",
    nome_pt: "Bolo Oreo",
    nome_en: "Oreo Cake",
    preco: "430 MT",
    descricao_pt: "Bolo de baunilha com biscoitos Oreo e cream cheese. Cremoso e crocante!",
    descricao_en: "Vanilla cake with Oreo cookies and cream cheese. Creamy and crunchy!",
    imagens: ["images/bolos/bolo15.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Oreo"]
  },
  {
    id: "bolo16",
    slug: "bolo-kitkat",
    categoria: "bolos",
    nome_pt: "Bolo Kit Kat",
    nome_en: "Kit Kat Cake",
    preco: "500 MT",
    descricao_pt: "Bolo de chocolate coberto com barras de Kit Kat e M&Ms coloridos.",
    descricao_en: "Chocolate cake covered with Kit Kat bars and colorful M&Ms.",
    imagens: ["images/bolos/bolo16.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Chocolate", "Kit Kat"]
  },
  {
    id: "bolo17",
    slug: "bolo-beijinho",
    categoria: "bolos",
    nome_pt: "Bolo de Beijinho",
    nome_en: "Coconut Kiss Cake",
    preco: "290 MT",
    descricao_pt: "Bolo de coco com leite condensado e cravo. Clássico brasileiro!",
    descricao_en: "Coconut cake with condensed milk and cloves. Brazilian classic!",
    imagens: ["images/bolos/bolo17.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Coco"]
  },
  {
    id: "bolo18",
    slug: "bolo-brigadeiro",
    categoria: "bolos",
    nome_pt: "Bolo de Brigadeiro",
    nome_en: "Brigadeiro Cake",
    preco: "380 MT",
    descricao_pt: "Bolo de chocolate com brigadeiro mole e granulados. Irresistível!",
    descricao_en: "Chocolate cake with soft brigadeiro and sprinkles. Irresistible!",
    imagens: ["images/bolos/bolo18.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Brigadeiro"]
  },
  {
    id: "bolo19",
    slug: "bolo-banana-canela",
    categoria: "bolos",
    nome_pt: "Bolo de Banana com Canela",
    nome_en: "Banana Cinnamon Cake",
    preco: "280 MT",
    descricao_pt: "Bolo de banana madura com canela e nozes. Caseiro e delicioso!",
    descricao_en: "Ripe banana cake with cinnamon and walnuts. Homemade and delicious!",
    imagens: ["images/bolos/bolo19.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Banana"]
  },
  {
    id: "bolo20",
    slug: "bolo-fuba-cremoso",
    categoria: "bolos",
    nome_pt: "Bolo de Fubá Cremoso",
    nome_en: "Creamy Cornmeal Cake",
    preco: "270 MT",
    descricao_pt: "Bolo de fubá cremoso com queijo ralado. Tradição mineira!",
    descricao_en: "Creamy cornmeal cake with grated cheese. Minas Gerais tradition!",
    imagens: ["images/bolos/bolo20.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Fubá"]
  },
  {
    id: "bolo21",
    slug: "bolo-milho-verde",
    categoria: "bolos",
    nome_pt: "Bolo de Milho Verde",
    nome_en: "Green Corn Cake",
    preco: "300 MT",
    descricao_pt: "Bolo de milho verde caseiro, fofinho e saboroso.",
    descricao_en: "Homemade green corn cake, fluffy and tasty.",
    imagens: ["images/bolos/bolo21.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Milho"]
  },
  {
    id: "bolo22",
    slug: "bolo-laranja",
    categoria: "bolos",
    nome_pt: "Bolo de Laranja",
    nome_en: "Orange Cake",
    preco: "260 MT",
    descricao_pt: "Bolo de laranja suculento com calda de laranja. Refrescante!",
    descricao_en: "Juicy orange cake with orange syrup. Refreshing!",
    imagens: ["images/bolos/bolo22.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Laranja"]
  },
  {
    id: "bolo23",
    slug: "bolo-maracuja",
    categoria: "bolos",
    nome_pt: "Bolo de Maracujá",
    nome_en: "Passion Fruit Cake",
    preco: "350 MT",
    descricao_pt: "Bolo de maracujá com calda de maracujá. Azedinho e delicioso!",
    descricao_en: "Passion fruit cake with passion fruit syrup. Tangy and delicious!",
    imagens: ["images/bolos/bolo23.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Maracujá"]
  },
  {
    id: "bolo24",
    slug: "bolo-amendoim",
    categoria: "bolos",
    nome_pt: "Bolo de Amendoim",
    nome_en: "Peanut Cake",
    preco: "290 MT",
    descricao_pt: "Bolo de amendoim torrado com cobertura de amendoim crocante.",
    descricao_en: "Toasted peanut cake with crunchy peanut topping.",
    imagens: ["images/bolos/bolo24.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Amendoim"]
  },
  {
    id: "bolo25",
    slug: "bolo-formigueiro",
    categoria: "bolos",
    nome_pt: "Bolo Formigueiro",
    nome_en: "Ant Cake",
    preco: "250 MT",
    descricao_pt: "Bolo de chocolate com granulados que parecem formiguinhas. Clássico!",
    descricao_en: "Chocolate cake with sprinkles that look like little ants. Classic!",
    imagens: ["images/bolos/bolo25.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Chocolate"]
  },
  {
    id: "bolo26",
    slug: "bolo-iogurte",
    categoria: "bolos",
    nome_pt: "Bolo de Iogurte",
    nome_en: "Yogurt Cake",
    preco: "280 MT",
    descricao_pt: "Bolo leve de iogurte natural, perfeito para o café da manhã.",
    descricao_en: "Light natural yogurt cake, perfect for breakfast.",
    imagens: ["images/bolos/bolo26.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Iogurte"]
  },
  {
    id: "bolo27",
    slug: "bolo-maça-canela",
    categoria: "bolos",
    nome_pt: "Bolo de Maçã com Canela",
    nome_en: "Apple Cinnamon Cake",
    preco: "320 MT",
    descricao_pt: "Bolo de maçã com pedaços de maçã e canela. Aconchegante!",
    descricao_en: "Apple cake with apple chunks and cinnamon. Cozy!",
    imagens: ["images/bolos/bolo27.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Maçã"]
  },
  {
    id: "bolo28",
    slug: "bolo-pessego",
    categoria: "bolos",
    nome_pt: "Bolo de Pêssego",
    nome_en: "Peach Cake",
    preco: "360 MT",
    descricao_pt: "Bolo de pêssego em calda com cobertura de chantilly.",
    descricao_en: "Peach cake in syrup with whipped cream topping.",
    imagens: ["images/bolos/bolo28.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Pêssego"]
  },
  {
    id: "bolo29",
    slug: "bolo-ameixa",
    categoria: "bolos",
    nome_pt: "Bolo de Ameixa",
    nome_en: "Plum Cake",
    preco: "340 MT",
    descricao_pt: "Bolo de ameixa seca com especiarias. Sabor único!",
    descricao_en: "Dried plum cake with spices. Unique flavor!",
    imagens: ["images/bolos/bolo29.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Ameixa"]
  },
  {
    id: "bolo30",
    slug: "bolo-figo-mel",
    categoria: "bolos",
    nome_pt: "Bolo de Figo com Mel",
    nome_en: "Fig Honey Cake",
    preco: "420 MT",
    descricao_pt: "Bolo de figo seco com mel e nozes. Sofisticado!",
    descricao_en: "Dried fig cake with honey and walnuts. Sophisticated!",
    imagens: ["images/bolos/bolo30.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Figo"]
  },
  {
    id: "bolo31",
    slug: "bolo-tiramisu",
    categoria: "bolos",
    nome_pt: "Bolo Tiramisù",
    nome_en: "Tiramisu Cake",
    preco: "480 MT",
    descricao_pt: "Bolo inspirado no clássico italiano com café e mascarpone.",
    descricao_en: "Cake inspired by the Italian classic with coffee and mascarpone.",
    imagens: ["images/bolos/bolo31.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Tiramisù"]
  },
  {
    id: "bolo32",
    slug: "bolo-cheesecake-morango",
    categoria: "bolos",
    nome_pt: "Cheesecake de Morango",
    nome_en: "Strawberry Cheesecake",
    preco: "550 MT",
    descricao_pt: "Cheesecake cremoso com calda de morango. Irresistível!",
    descricao_en: "Creamy cheesecake with strawberry sauce. Irresistible!",
    imagens: ["images/bolos/bolo32.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Morango"]
  },
  {
    id: "bolo33",
    slug: "bolo-pistache",
    categoria: "bolos",
    nome_pt: "Bolo de Pistache",
    nome_en: "Pistachio Cake",
    preco: "520 MT",
    descricao_pt: "Bolo de pistache com cobertura de pistache triturado. Exótico!",
    descricao_en: "Pistachio cake with crushed pistachio topping. Exotic!",
    imagens: ["images/bolos/bolo33.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Pistache"]
  },
  {
    id: "bolo34",
    slug: "bolo-frutas-vermelhas",
    categoria: "bolos",
    nome_pt: "Bolo de Frutas Vermelhas",
    nome_en: "Red Berries Cake",
    preco: "460 MT",
    descricao_pt: "Bolo com mix de frutas vermelhas: morango, framboesa e amora.",
    descricao_en: "Cake with mixed red berries: strawberry, raspberry and blackberry.",
    imagens: ["images/bolos/bolo34.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Frutas Vermelhas"]
  },
  {
    id: "bolo35",
    slug: "bolo-chocolate-branco",
    categoria: "bolos",
    nome_pt: "Bolo de Chocolate Branco",
    nome_en: "White Chocolate Cake",
    preco: "410 MT",
    descricao_pt: "Bolo de chocolate branco com raspas de chocolate branco.",
    descricao_en: "White chocolate cake with white chocolate shavings.",
    imagens: ["images/bolos/bolo35.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Chocolate Branco"]
  },
  {
    id: "bolo36",
    slug: "bolo-caramelo-salgado",
    categoria: "bolos",
    nome_pt: "Bolo de Caramelo Salgado",
    nome_en: "Salted Caramel Cake",
    preco: "440 MT",
    descricao_pt: "Bolo de caramelo com toque de flor de sal. Tendência!",
    descricao_en: "Caramel cake with a touch of sea salt. Trendy!",
    imagens: ["images/bolos/bolo36.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Caramelo"]
  },
  {
    id: "bolo37",
    slug: "bolo-brownie",
    categoria: "bolos",
    nome_pt: "Bolo Brownie",
    nome_en: "Brownie Cake",
    preco: "390 MT",
    descricao_pt: "Bolo estilo brownie com nozes e cobertura de chocolate.",
    descricao_en: "Brownie-style cake with walnuts and chocolate topping.",
    imagens: ["images/bolos/bolo37.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Brownie"]
  },
  {
    id: "bolo38",
    slug: "bolo-moka",
    categoria: "bolos",
    nome_pt: "Bolo Moka",
    nome_en: "Mocha Cake",
    preco: "400 MT",
    descricao_pt: "Bolo de café com chocolate, recheio de manteiga de café.",
    descricao_en: "Coffee and chocolate cake with coffee butter filling.",
    imagens: ["images/bolos/bolo38.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Moka"]
  },
  {
    id: "bolo39",
    slug: "bolo-ricota",
    categoria: "bolos",
    nome_pt: "Bolo de Ricota",
    nome_en: "Ricotta Cake",
    preco: "350 MT",
    descricao_pt: "Bolo de ricota com limão siciliano. Leve e delicado!",
    descricao_en: "Ricotta cake with Sicilian lemon. Light and delicate!",
    imagens: ["images/bolos/bolo39.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Ricota"]
  },
  {
    id: "bolo40",
    slug: "bolo-mandioca",
    categoria: "bolos",
    nome_pt: "Bolo de Mandioca",
    nome_en: "Cassava Cake",
    preco: "280 MT",
    descricao_pt: "Bolo de mandioca com coco. Tradição brasileira!",
    descricao_en: "Cassava cake with coconut. Brazilian tradition!",
    imagens: ["images/bolos/bolo40.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Mandioca"]
  },
  {
    id: "bolo41",
    slug: "bolo-tapioca",
    categoria: "bolos",
    nome_pt: "Bolo de Tapioca",
    nome_en: "Tapioca Cake",
    preco: "300 MT",
    descricao_pt: "Bolo de tapioca granulada com leite de coco. Nordestino!",
    descricao_en: "Granulated tapioca cake with coconut milk. Northeastern!",
    imagens: ["images/bolos/bolo41.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Tapioca"]
  },
  {
    id: "bolo42",
    slug: "bolo-queijo",
    categoria: "bolos",
    nome_pt: "Bolo de Queijo",
    nome_en: "Cheese Cake",
    preco: "330 MT",
    descricao_pt: "Bolo de queijo minas, salgadinho e delicioso.",
    descricao_en: "Minas cheese cake, savory and delicious.",
    imagens: ["images/bolos/bolo42.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Queijo"]
  },
  {
    id: "bolo43",
    slug: "bolo-manga",
    categoria: "bolos",
    nome_pt: "Bolo de Manga",
    nome_en: "Mango Cake",
    preco: "340 MT",
    descricao_pt: "Bolo de manga fresca com calda de manga. Tropical!",
    descricao_en: "Fresh mango cake with mango syrup. Tropical!",
    imagens: ["images/bolos/bolo43.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Manga"]
  },
  {
    id: "bolo44",
    slug: "bolo-uva",
    categoria: "bolos",
    nome_pt: "Bolo de Uva",
    nome_en: "Grape Cake",
    preco: "370 MT",
    descricao_pt: "Bolo de uva verde ou roxa com cobertura de uvas frescas.",
    descricao_en: "Green or purple grape cake with fresh grape topping.",
    imagens: ["images/bolos/bolo44.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Uva"]
  },
  {
    id: "bolo45",
    slug: "bolo-pera",
    categoria: "bolos",
    nome_pt: "Bolo de Pêra",
    nome_en: "Pear Cake",
    preco: "360 MT",
    descricao_pt: "Bolo de pêra com especiarias e nozes. Aromático!",
    descricao_en: "Pear cake with spices and walnuts. Aromatic!",
    imagens: ["images/bolos/bolo45.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Pêra"]
  },
  {
    id: "bolo46",
    slug: "bolo-amendoa",
    categoria: "bolos",
    nome_pt: "Bolo de Amêndoa",
    nome_en: "Almond Cake",
    preco: "450 MT",
    descricao_pt: "Bolo de amêndoa com essência de amêndoa. Delicado!",
    descricao_en: "Almond cake with almond essence. Delicate!",
    imagens: ["images/bolos/bolo46.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Amêndoa"]
  },
  {
    id: "bolo47",
    slug: "bolo-especiarias",
    categoria: "bolos",
    nome_pt: "Bolo de Especiarias",
    nome_en: "Spice Cake",
    preco: "380 MT",
    descricao_pt: "Bolo com canela, gengibre, noz-moscada e cravo. Aquece o coração!",
    descricao_en: "Cake with cinnamon, ginger, nutmeg and cloves. Warms the heart!",
    imagens: ["images/bolos/bolo47.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Especiarias"]
  },
  {
    id: "bolo48",
    slug: "bolo-chocolate-menta",
    categoria: "bolos",
    nome_pt: "Bolo de Chocolate com Menta",
    nome_en: "Chocolate Mint Cake",
    preco: "420 MT",
    descricao_pt: "Bolo de chocolate com toque refrescante de menta. Surpreendente!",
    descricao_en: "Chocolate cake with refreshing mint touch. Surprising!",
    imagens: ["images/bolos/bolo48.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Chocolate Menta"]
  },
  {
    id: "bolo49",
    slug: "bolo-cereja",
    categoria: "bolos",
    nome_pt: "Bolo de Cereja",
    nome_en: "Cherry Cake",
    preco: "470 MT",
    descricao_pt: "Bolo de cereja fresca ou em calda. Clássico europeu!",
    descricao_en: "Fresh or syrup cherry cake. European classic!",
    imagens: ["images/bolos/bolo49.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Cereja"]
  },
  {
    id: "bolo50",
    slug: "bolo-natalino",
    categoria: "bolos",
    nome_pt: "Bolo Natalino",
    nome_en: "Christmas Cake",
    preco: "500 MT",
    descricao_pt: "Bolo de frutas cristalizadas com especiarias. Perfeito para o Natal!",
    descricao_en: "Crystallized fruit cake with spices. Perfect for Christmas!",
    imagens: ["images/bolos/bolo50.jpg"],
    tamanhos: ["Pequeno", "Médio", "Grande"],
    sabores: ["Natalino"]
  },

  // ============================================
  // DOCES (50 produtos)
  // ============================================
  {
    id: "doce1",
    slug: "brigadeiro-tradicional",
    categoria: "doces",
    nome_pt: "Brigadeiro Tradicional",
    nome_en: "Traditional Brigadeiro",
    preco: "15 MT",
    descricao_pt: "Brigadeiro de chocolate com granulados. O clássico brasileiro!",
    descricao_en: "Chocolate brigadeiro with sprinkles. The Brazilian classic!",
    imagens: ["images/doces/doce1.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 6", "Caixa c/ 12"],
    sabores: ["Chocolate"]
  },
  {
    id: "doce2",
    slug: "beijinho-coco",
    categoria: "doces",
    nome_pt: "Beijinho de Coco",
    nome_en: "Coconut Kiss",
    preco: "15 MT",
    descricao_pt: "Doce de coco com leite condensado e cravo. Delicioso!",
    descricao_en: "Coconut sweet with condensed milk and cloves. Delicious!",
    imagens: ["images/doces/doce2.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 6", "Caixa c/ 12"],
    sabores: ["Coco"]
  },
  {
    id: "doce3",
    slug: "casadinho",
    categoria: "doces",
    nome_pt: "Casadinho",
    nome_en: "Casadinho",
    preco: "18 MT",
    descricao_pt: "Brigadeiro branco e preto casados. Combinação perfeita!",
    descricao_en: "White and dark brigadeiro married. Perfect combination!",
    imagens: ["images/doces/doce3.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 6", "Caixa c/ 12"],
    sabores: ["Chocolate", "Leite Ninho"]
  },
  {
    id: "doce4",
    slug: "brigadeiro-ninho-nutella",
    categoria: "doces",
    nome_pt: "Brigadeiro Ninho com Nutella",
    nome_en: "Nest Milk Nutella Brigadeiro",
    preco: "25 MT",
    descricao_pt: "Brigadeiro de leite ninho recheado com Nutella. Irresistível!",
    descricao_en: "Nest milk brigadeiro filled with Nutella. Irresistible!",
    imagens: ["images/doces/doce4.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 6", "Caixa c/ 12"],
    sabores: ["Ninho", "Nutella"]
  },
  {
    id: "doce5",
    slug: "brigadeiro-oreo",
    categoria: "doces",
    nome_pt: "Brigadeiro Oreo",
    nome_en: "Oreo Brigadeiro",
    preco: "22 MT",
    descricao_pt: "Brigadeiro com biscoito Oreo triturado. Crocante!",
    descricao_en: "Brigadeiro with crushed Oreo cookies. Crunchy!",
    imagens: ["images/doces/doce5.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 6", "Caixa c/ 12"],
    sabores: ["Oreo"]
  },
  {
    id: "doce6",
    slug: "brigadeiro-pistache",
    categoria: "doces",
    nome_pt: "Brigadeiro de Pistache",
    nome_en: "Pistachio Brigadeiro",
    preco: "30 MT",
    descricao_pt: "Brigadeiro de pistache com pedacinhos de pistache. Sofisticado!",
    descricao_en: "Pistachio brigadeiro with pistache pieces. Sophisticated!",
    imagens: ["images/doces/doce6.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 6", "Caixa c/ 12"],
    sabores: ["Pistache"]
  },
  {
    id: "doce7",
    slug: "brigadeiro-churros",
    categoria: "doces",
    nome_pt: "Brigadeiro de Churros",
    nome_en: "Churros Brigadeiro",
    preco: "20 MT",
    descricao_pt: "Brigadeiro com canela e doce de leite. Sabor de churros!",
    descricao_en: "Brigadeiro with cinnamon and dulce de leche. Churros flavor!",
    imagens: ["images/doces/doce7.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 6", "Caixa c/ 12"],
    sabores: ["Churros"]
  },
  {
    id: "doce8",
    slug: "brigadeiro-paçoca",
    categoria: "doces",
    nome_pt: "Brigadeiro de Paçoca",
    nome_en: "Peanut Brigadeiro",
    preco: "18 MT",
    descricao_pt: "Brigadeiro de amendoim com paçoca. Sabor brasileiro!",
    descricao_en: "Peanut brigadeiro with paçoca. Brazilian flavor!",
    imagens: ["images/doces/doce8.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 6", "Caixa c/ 12"],
    sabores: ["Paçoca"]
  },
  {
    id: "doce9",
    slug: "brigadeiro-cafe",
    categoria: "doces",
    nome_pt: "Brigadeiro de Café",
    nome_en: "Coffee Brigadeiro",
    preco: "20 MT",
    descricao_pt: "Brigadeiro de café intenso. Para amantes de café!",
    descricao_en: "Intense coffee brigadeiro. For coffee lovers!",
    imagens: ["images/doces/doce9.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 6", "Caixa c/ 12"],
    sabores: ["Café"]
  },
  {
    id: "doce10",
    slug: "brigadeiro-maracuja",
    categoria: "doces",
    nome_pt: "Brigadeiro de Maracujá",
    nome_en: "Passion Fruit Brigadeiro",
    preco: "20 MT",
    descricao_pt: "Brigadeiro de maracujá azedinho. Refrescante!",
    descricao_en: "Tangy passion fruit brigadeiro. Refreshing!",
    imagens: ["images/doces/doce10.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 6", "Caixa c/ 12"],
    sabores: ["Maracujá"]
  },
  {
    id: "doce11",
    slug: "brigadeiro-limao",
    categoria: "doces",
    nome_pt: "Brigadeiro de Limão",
    nome_en: "Lemon Brigadeiro",
    preco: "18 MT",
    descricao_pt: "Brigadeiro de limão siciliano. Azedinho e delicioso!",
    descricao_en: "Sicilian lemon brigadeiro. Tangy and delicious!",
    imagens: ["images/doces/doce11.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 6", "Caixa c/ 12"],
    sabores: ["Limão"]
  },
  {
    id: "doce12",
    slug: "brigadeiro-morango",
    categoria: "doces",
    nome_pt: "Brigadeiro de Morango",
    nome_en: "Strawberry Brigadeiro",
    preco: "22 MT",
    descricao_pt: "Brigadeiro de morango com pedacinhos de morango. Frutado!",
    descricao_en: "Strawberry brigadeiro with strawberry pieces. Fruity!",
    imagens: ["images/doces/doce12.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 6", "Caixa c/ 12"],
    sabores: ["Morango"]
  },
  {
    id: "doce13",
    slug: "brigadeiro-avela",
    categoria: "doces",
    nome_pt: "Brigadeiro de Avelã",
    nome_en: "Hazelnut Brigadeiro",
    preco: "28 MT",
    descricao_pt: "Brigadeiro de avelã tipo Nutella. Cremoso!",
    descricao_en: "Hazelnut brigadeiro like Nutella. Creamy!",
    imagens: ["images/doces/doce13.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 6", "Caixa c/ 12"],
    sabores: ["Avelã"]
  },
  {
    id: "doce14",
    slug: "brigadeiro-coco-queimado",
    categoria: "doces",
    nome_pt: "Brigadeiro de Coco Queimado",
    nome_en: "Burnt Coconut Brigadeiro",
    preco: "20 MT",
    descricao_pt: "Brigadeiro de coco tostado. Sabor único!",
    descricao_en: "Toasted coconut brigadeiro. Unique flavor!",
    imagens: ["images/doces/doce14.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 6", "Caixa c/ 12"],
    sabores: ["Coco Queimado"]
  },
  {
    id: "doce15",
    slug: "brigadeiro-brigadeiro",
    categoria: "doces",
    nome_pt: "Brigadeiro de Brigadeiro",
    nome_en: "Brigadeiro Brigadeiro",
    preco: "25 MT",
    descricao_pt: "Brigadeiro duplo, com recheio de brigadeiro. Extra chocolate!",
    descricao_en: "Double brigadeiro, filled with brigadeiro. Extra chocolate!",
    imagens: ["images/doces/doce15.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 6", "Caixa c/ 12"],
    sabores: ["Brigadeiro"]
  },
  {
    id: "doce16",
    slug: "trufa-chocolate",
    categoria: "doces",
    nome_pt: "Trufa de Chocolate",
    nome_en: "Chocolate Truffle",
    preco: "35 MT",
    descricao_pt: "Trufa de chocolate meio amargo com recheio cremoso.",
    descricao_en: "Semi-sweet chocolate truffle with creamy filling.",
    imagens: ["images/doces/doce16.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 4", "Caixa c/ 8"],
    sabores: ["Chocolate", "Chocolate Branco"]
  },
  {
    id: "doce17",
    slug: "trufa-morango",
    categoria: "doces",
    nome_pt: "Trufa de Morango",
    nome_en: "Strawberry Truffle",
    preco: "38 MT",
    descricao_pt: "Trufa de chocolate branco com recheio de morango.",
    descricao_en: "White chocolate truffle with strawberry filling.",
    imagens: ["images/doces/doce17.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 4", "Caixa c/ 8"],
    sabores: ["Morango"]
  },
  {
    id: "doce18",
    slug: "trufa-maracuja",
    categoria: "doces",
    nome_pt: "Trufa de Maracujá",
    nome_en: "Passion Fruit Truffle",
    preco: "38 MT",
    descricao_pt: "Trufa de chocolate branco com recheio de maracujá.",
    descricao_en: "White chocolate truffle with passion fruit filling.",
    imagens: ["images/doces/doce18.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 4", "Caixa c/ 8"],
    sabores: ["Maracujá"]
  },
  {
    id: "doce19",
    slug: "trufa-cafe",
    categoria: "doces",
    nome_pt: "Trufa de Café",
    nome_en: "Coffee Truffle",
    preco: "38 MT",
    descricao_pt: "Trufa de chocolate com recheio de café. Intensa!",
    descricao_en: "Chocolate truffle with coffee filling. Intense!",
    imagens: ["images/doces/doce19.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 4", "Caixa c/ 8"],
    sabores: ["Café"]
  },
  {
    id: "doce20",
    slug: "trufa-nozes",
    categoria: "doces",
    nome_pt: "Trufa de Nozes",
    nome_en: "Walnut Truffle",
    preco: "42 MT",
    descricao_pt: "Trufa de chocolate com nozes caramelizadas.",
    descricao_en: "Chocolate truffle with caramelized walnuts.",
    imagens: ["images/doces/doce20.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 4", "Caixa c/ 8"],
    sabores: ["Nozes"]
  },
  {
    id: "doce21",
    slug: "bombom-sortido",
    categoria: "doces",
    nome_pt: "Bombom Sortido",
    nome_en: "Assorted Chocolates",
    preco: "80 MT",
    descricao_pt: "Caixa com bombons variados: chocolate, morango, coco, nozes.",
    descricao_en: "Box with assorted chocolates: chocolate, strawberry, coconut, walnuts.",
    imagens: ["images/doces/doce21.jpg"],
    tamanhos: ["Caixa c/ 8", "Caixa c/ 12", "Caixa c/ 24"],
    sabores: ["Sortido"]
  },
  {
    id: "doce22",
    slug: "alfajor-argentino",
    categoria: "doces",
    nome_pt: "Alfajor Argentino",
    nome_en: "Argentine Alfajor",
    preco: "45 MT",
    descricao_pt: "Dois biscoitos com doce de leite e cobertura de chocolate.",
    descricao_en: "Two cookies with dulce de leche and chocolate coating.",
    imagens: ["images/doces/doce22.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 3", "Caixa c/ 6"],
    sabores: ["Doce de Leite"]
  },
  {
    id: "doce23",
    slug: "palha-italiana",
    categoria: "doces",
    nome_pt: "Palha Italiana",
    nome_en: "Italian Straw",
    preco: "60 MT",
    descricao_pt: "Palitinhos de chocolate com biscoito. Crocantes!",
    descricao_en: "Chocolate sticks with cookies. Crunchy!",
    imagens: ["images/doces/doce23.jpg"],
    tamanhos: ["Pacote P", "Pacote M", "Pacote G"],
    sabores: ["Chocolate"]
  },
  {
    id: "doce24",
    slug: "pao-mel",
    categoria: "doces",
    nome_pt: "Pão de Mel",
    nome_en: "Honey Bread",
    preco: "40 MT",
    descricao_pt: "Pão de mel recheado com doce de leite e cobertura de chocolate.",
    descricao_en: "Honey bread filled with dulce de leche and chocolate coating.",
    imagens: ["images/doces/doce24.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 3", "Caixa c/ 6"],
    sabores: ["Chocolate", "Doce de Leite"]
  },
  {
    id: "doce25",
    slug: "brownie-recheado",
    categoria: "doces",
    nome_pt: "Brownie Recheado",
    nome_en: "Filled Brownie",
    preco: "55 MT",
    descricao_pt: "Brownie de chocolate recheado com brigadeiro ou Nutella.",
    descricao_en: "Chocolate brownie filled with brigadeiro or Nutella.",
    imagens: ["images/doces/doce25.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 2", "Caixa c/ 4"],
    sabores: ["Chocolate", "Nutella"]
  },
  {
    id: "doce26",
    slug: "cookie-chocolate",
    categoria: "doces",
    nome_pt: "Cookie de Chocolate",
    nome_en: "Chocolate Cookie",
    preco: "35 MT",
    descricao_pt: "Cookie com gotas de chocolate. Crocante por fora, macio por dentro!",
    descricao_en: "Cookie with chocolate chips. Crunchy outside, soft inside!",
    imagens: ["images/doces/doce26.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 3", "Caixa c/ 6"],
    sabores: ["Chocolate"]
  },
  {
    id: "doce27",
    slug: "cookie-avela",
    categoria: "doces",
    nome_pt: "Cookie de Avelã",
    nome_en: "Hazelnut Cookie",
    preco: "40 MT",
    descricao_pt: "Cookie de avelã com pedacinhos de avelã.",
    descricao_en: "Hazelnut cookie with hazelnut pieces.",
    imagens: ["images/doces/doce27.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 3", "Caixa c/ 6"],
    sabores: ["Avelã"]
  },
  {
    id: "doce28",
    slug: "cookie-aveia",
    categoria: "doces",
    nome_pt: "Cookie de Aveia",
    nome_en: "Oatmeal Cookie",
    preco: "30 MT",
    descricao_pt: "Cookie de aveia com passas. Saudável e delicioso!",
    descricao_en: "Oatmeal cookie with raisins. Healthy and delicious!",
    imagens: ["images/doces/doce28.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 3", "Caixa c/ 6"],
    sabores: ["Aveia"]
  },
  {
    id: "doce29",
    slug: "cookie-red-velvet",
    categoria: "doces",
    nome_pt: "Cookie Red Velvet",
    nome_en: "Red Velvet Cookie",
    preco: "45 MT",
    descricao_pt: "Cookie red velvet com cream cheese. Elegante!",
    descricao_en: "Red velvet cookie with cream cheese. Elegant!",
    imagens: ["images/doces/doce29.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 3", "Caixa c/ 6"],
    sabores: ["Red Velvet"]
  },
  {
    id: "doce30",
    slug: "macaron-sortido",
    categoria: "doces",
    nome_pt: "Macaron Sortido",
    nome_en: "Assorted Macarons",
    preco: "120 MT",
    descricao_pt: "Caixa com macarons franceses em vários sabores.",
    descricao_en: "Box with French macarons in various flavors.",
    imagens: ["images/doces/doce30.jpg"],
    tamanhos: ["Caixa c/ 3", "Caixa c/ 6", "Caixa c/ 12"],
    sabores: ["Sortido"]
  },
  {
    id: "doce31",
    slug: "rocambole-doce-leite",
    categoria: "doces",
    nome_pt: "Rocambole de Doce de Leite",
    nome_en: "Dulce de Leche Roll",
    preco: "180 MT",
    descricao_pt: "Rocambole de massa fofinha com recheio de doce de leite.",
    descricao_en: "Soft roll cake with dulce de leche filling.",
    imagens: ["images/doces/doce31.jpg"],
    tamanhos: ["Fatia", "Inteiro"],
    sabores: ["Doce de Leite"]
  },
  {
    id: "doce32",
    slug: "rocambole-chocolate",
    categoria: "doces",
    nome_pt: "Rocambole de Chocolate",
    nome_en: "Chocolate Roll",
    preco: "190 MT",
    descricao_pt: "Rocambole de chocolate com recheio de brigadeiro.",
    descricao_en: "Chocolate roll cake with brigadeiro filling.",
    imagens: ["images/doces/doce32.jpg"],
    tamanhos: ["Fatia", "Inteiro"],
    sabores: ["Chocolate"]
  },
  {
    id: "doce33",
    slug: "rocambole-morango",
    categoria: "doces",
    nome_pt: "Rocambole de Morango",
    nome_en: "Strawberry Roll",
    preco: "200 MT",
    descricao_pt: "Rocambole de baunilha com recheio de morango e chantilly.",
    descricao_en: "Vanilla roll cake with strawberry and whipped cream filling.",
    imagens: ["images/doces/doce33.jpg"],
    tamanhos: ["Fatia", "Inteiro"],
    sabores: ["Morango"]
  },
  {
    id: "doce34",
    slug: "torta-alema",
    categoria: "doces",
    nome_pt: "Torta Alemã",
    nome_en: "German Pie",
    preco: "250 MT",
    descricao_pt: "Torta gelada de bolacha com creme e chocolate.",
    descricao_en: "Cold cookie pie with cream and chocolate.",
    imagens: ["images/doces/doce34.jpg"],
    tamanhos: ["Fatia", "Inteira"],
    sabores: ["Chocolate"]
  },
  {
    id: "doce35",
    slug: "torta-limao",
    categoria: "doces",
    nome_pt: "Torta de Limão",
    nome_en: "Lemon Pie",
    preco: "220 MT",
    descricao_pt: "Torta de limão com merengue. Refrescante!",
    descricao_en: "Lemon pie with meringue. Refreshing!",
    imagens: ["images/doces/doce35.jpg"],
    tamanhos: ["Fatia", "Inteira"],
    sabores: ["Limão"]
  },
  {
    id: "doce36",
    slug: "torta-morango",
    categoria: "doces",
    nome_pt: "Torta de Morango",
    nome_en: "Strawberry Pie",
    preco: "240 MT",
    descricao_pt: "Torta de morango com creme e gelatina de morango.",
    descricao_en: "Strawberry pie with cream and strawberry gelatin.",
    imagens: ["images/doces/doce36.jpg"],
    tamanhos: ["Fatia", "Inteira"],
    sabores: ["Morango"]
  },
  {
    id: "doce37",
    slug: "pudim-leite",
    categoria: "doces",
    nome_pt: "Pudim de Leite",
    nome_en: "Milk Pudding",
    preco: "150 MT",
    descricao_pt: "Pudim de leite condensado com calda de caramelo. Clássico!",
    descricao_en: "Condensed milk pudding with caramel sauce. Classic!",
    imagens: ["images/doces/doce37.jpg"],
    tamanhos: ["Individual", "Família"],
    sabores: ["Leite"]
  },
  {
    id: "doce38",
    slug: "pudim-pao",
    categoria: "doces",
    nome_pt: "Pudim de Pão",
    nome_en: "Bread Pudding",
    preco: "140 MT",
    descricao_pt: "Pudim de pão com leite condensado e canela.",
    descricao_en: "Bread pudding with condensed milk and cinnamon.",
    imagens: ["images/doces/doce38.jpg"],
    tamanhos: ["Individual", "Família"],
    sabores: ["Pão"]
  },
  {
    id: "doce39",
    slug: "pudim-chocolate",
    categoria: "doces",
    nome_pt: "Pudim de Chocolate",
    nome_en: "Chocolate Pudding",
    preco: "160 MT",
    descricao_pt: "Pudim de chocolate com calda de chocolate.",
    descricao_en: "Chocolate pudding with chocolate sauce.",
    imagens: ["images/doces/doce39.jpg"],
    tamanhos: ["Individual", "Família"],
    sabores: ["Chocolate"]
  },
  {
    id: "doce40",
    slug: "mousse-maracuja",
    categoria: "doces",
    nome_pt: "Mousse de Maracujá",
    nome_en: "Passion Fruit Mousse",
    preco: "120 MT",
    descricao_pt: "Mousse de maracujá com calda de maracujá. Azedinha!",
    descricao_en: "Passion fruit mousse with passion fruit sauce. Tangy!",
    imagens: ["images/doces/doce40.jpg"],
    tamanhos: ["Individual", "Família"],
    sabores: ["Maracujá"]
  },
  {
    id: "doce41",
    slug: "mousse-chocolate",
    categoria: "doces",
    nome_pt: "Mousse de Chocolate",
    nome_en: "Chocolate Mousse",
    preco: "130 MT",
    descricao_pt: "Mousse de chocolate meio amargo. Cremosa!",
    descricao_en: "Semi-sweet chocolate mousse. Creamy!",
    imagens: ["images/doces/doce41.jpg"],
    tamanhos: ["Individual", "Família"],
    sabores: ["Chocolate"]
  },
  {
    id: "doce42",
    slug: "mousse-morango",
    categoria: "doces",
    nome_pt: "Mousse de Morango",
    nome_en: "Strawberry Mousse",
    preco: "130 MT",
    descricao_pt: "Mousse de morango com pedacinhos de morango.",
    descricao_en: "Strawberry mousse with strawberry pieces.",
    imagens: ["images/doces/doce42.jpg"],
    tamanhos: ["Individual", "Família"],
    sabores: ["Morango"]
  },
  {
    id: "doce43",
    slug: "quindim",
    categoria: "doces",
    nome_pt: "Quindim",
    nome_en: "Quindim",
    preco: "25 MT",
    descricao_pt: "Doce de gema de ovo e coco. Tradição brasileira!",
    descricao_en: "Egg yolk and coconut sweet. Brazilian tradition!",
    imagens: ["images/doces/doce43.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 6"],
    sabores: ["Coco"]
  },
  {
    id: "doce44",
    slug: "cocada",
    categoria: "doces",
    nome_pt: "Cocada",
    nome_en: "Cocada",
    preco: "20 MT",
    descricao_pt: "Doce de coco em pedaços. Nordestina!",
    descricao_en: "Coconut sweet in chunks. Northeastern!",
    imagens: ["images/doces/doce44.jpg"],
    tamanhos: ["Unidade", "Pacote"],
    sabores: ["Coco"]
  },
  {
    id: "doce45",
    slug: "pe-de-moleque",
    categoria: "doces",
    nome_pt: "Pé de Moleque",
    nome_en: "Peanut Brittle",
    preco: "25 MT",
    descricao_pt: "Doce de amendoim crocante. Festa Junina!",
    descricao_en: "Crunchy peanut sweet. June Festival!",
    imagens: ["images/doces/doce45.jpg"],
    tamanhos: ["Unidade", "Pacote"],
    sabores: ["Amendoim"]
  },
  {
    id: "doce46",
    slug: "rapadura",
    categoria: "doces",
    nome_pt: "Rapadura",
    nome_en: "Rapadura",
    preco: "15 MT",
    descricao_pt: "Doce de rapadura com amendoim. Tradição!",
    descricao_en: "Rapadura sweet with peanuts. Tradition!",
    imagens: ["images/doces/doce46.jpg"],
    tamanhos: ["Unidade", "Pacote"],
    sabores: ["Rapadura"]
  },
  {
    id: "doce47",
    slug: "doce-abobora",
    categoria: "doces",
    nome_pt: "Doce de Abóbora",
    nome_en: "Pumpkin Sweet",
    preco: "30 MT",
    descricao_pt: "Doce de abóbora com coco. Caseiro!",
    descricao_en: "Pumpkin sweet with coconut. Homemade!",
    imagens: ["images/doces/doce47.jpg"],
    tamanhos: ["Pote P", "Pote M", "Pote G"],
    sabores: ["Abóbora"]
  },
  {
    id: "doce48",
    slug: "doce-banana",
    categoria: "doces",
    nome_pt: "Doce de Banana",
    nome_en: "Banana Sweet",
    preco: "30 MT",
    descricao_pt: "Doce de banana com canela e cravo.",
    descricao_en: "Banana sweet with cinnamon and cloves.",
    imagens: ["images/doces/doce48.jpg"],
    tamanhos: ["Pote P", "Pote M", "Pote G"],
    sabores: ["Banana"]
  },
  {
    id: "doce49",
    slug: "doce-figo",
    categoria: "doces",
    nome_pt: "Doce de Figo",
    nome_en: "Fig Sweet",
    preco: "45 MT",
    descricao_pt: "Doce de figo em calda. Sofisticado!",
    descricao_en: "Fig sweet in syrup. Sophisticated!",
    imagens: ["images/doces/doce49.jpg"],
    tamanhos: ["Pote P", "Pote M", "Pote G"],
    sabores: ["Figo"]
  },
  {
    id: "doce50",
    slug: "doce-leite-cremoso",
    categoria: "doces",
    nome_pt: "Doce de Leite Cremoso",
    nome_en: "Creamy Dulce de Leche",
    preco: "50 MT",
    descricao_pt: "Doce de leite caseiro, cremoso e delicioso.",
    descricao_en: "Homemade dulce de leche, creamy and delicious.",
    imagens: ["images/doces/doce50.jpg"],
    tamanhos: ["Pote P", "Pote M", "Pote G"],
    sabores: ["Doce de Leite"]
  },

  // ============================================
  // NOVIDADES (50 produtos)
  // ============================================
  {
    id: "nov1",
    slug: "bolo-kitkat-oreo",
    categoria: "novidades",
    nome_pt: "Bolo Kit Kat Oreo",
    nome_en: "Kit Kat Oreo Cake",
    preco: "650 MT",
    descricao_pt: "Bolo de chocolate com Kit Kat e Oreo. Explosão de sabor! NOVIDADE!",
    descricao_en: "Chocolate cake with Kit Kat and Oreo. Flavor explosion! NEW!",
    imagens: ["images/novidades/nov1.jpg"],
    tamanhos: ["Médio", "Grande"],
    sabores: ["Kit Kat", "Oreo"]
  },
  {
    id: "nov2",
    slug: "bolo-unicornio",
    categoria: "novidades",
    nome_pt: "Bolo Unicórnio",
    nome_en: "Unicorn Cake",
    preco: "580 MT",
    descricao_pt: "Bolo colorido de unicórnio com chantilly arco-íris. Mágico! NOVIDADE!",
    descricao_en: "Colorful unicorn cake with rainbow whipped cream. Magical! NEW!",
    imagens: ["images/novidades/nov2.jpg"],
    tamanhos: ["Médio", "Grande"],
    sabores: ["Baunilha", "Morango"]
  },
  {
    id: "nov3",
    slug: "bolo-drip-cake",
    categoria: "novidades",
    nome_pt: "Drip Cake Gold",
    nome_en: "Gold Drip Cake",
    preco: "600 MT",
    descricao_pt: "Bolo drip cake com cobertura dourada. Luxuoso! NOVIDADE!",
    descricao_en: "Drip cake with golden topping. Luxurious! NEW!",
    imagens: ["images/novidades/nov3.jpg"],
    tamanhos: ["Médio", "Grande"],
    sabores: ["Chocolate", "Baunilha"]
  },
  {
    id: "nov4",
    slug: "bolo-geode",
    categoria: "novidades",
    nome_pt: "Bolo Geode",
    nome_en: "Geode Cake",
    preco: "750 MT",
    descricao_pt: "Bolo esculpido em formato de cristal geode. Arte comestível! NOVIDADE!",
    descricao_en: "Sculpted cake in geode crystal shape. Edible art! NEW!",
    imagens: ["images/novidades/nov4.jpg"],
    tamanhos: ["Grande"],
    sabores: ["Baunilha", "Amêndoa"]
  },
  {
    id: "nov5",
    slug: "bolo-princesa",
    categoria: "novidades",
    nome_pt: "Bolo Princesa",
    nome_en: "Princess Cake",
    preco: "550 MT",
    descricao_pt: "Bolo temático de princesa com coroa comestível. Encantador! NOVIDADE!",
    descricao_en: "Princess themed cake with edible crown. Enchanting! NEW!",
    imagens: ["images/novidades/nov5.jpg"],
    tamanhos: ["Médio", "Grande"],
    sabores: ["Baunilha", "Morango"]
  },
  {
    id: "nov6",
    slug: "bolo-super-heroi",
    categoria: "novidades",
    nome_pt: "Bolo Super-Herói",
    nome_en: "Superhero Cake",
    preco: "580 MT",
    descricao_pt: "Bolo temático de super-herói. Para pequenos heróis! NOVIDADE!",
    descricao_en: "Superhero themed cake. For little heroes! NEW!",
    imagens: ["images/novidades/nov6.jpg"],
    tamanhos: ["Médio", "Grande"],
    sabores: ["Chocolate", "Baunilha"]
  },
  {
    id: "nov7",
    slug: "bolo-baby-shower",
    categoria: "novidades",
    nome_pt: "Bolo Baby Shower",
    nome_en: "Baby Shower Cake",
    preco: "520 MT",
    descricao_pt: "Bolo para chá de bebê, rosa ou azul. Delicado! NOVIDADE!",
    descricao_en: "Baby shower cake, pink or blue. Delicate! NEW!",
    imagens: ["images/novidades/nov7.jpg"],
    tamanhos: ["Médio", "Grande"],
    sabores: ["Baunilha", "Chocolate"]
  },
  {
    id: "nov8",
    slug: "bolo-noivado",
    categoria: "novidades",
    nome_pt: "Bolo de Noivado",
    nome_en: "Engagement Cake",
    preco: "680 MT",
    descricao_pt: "Bolo elegante para noivado com flores comestíveis. Romântico! NOVIDADE!",
    descricao_en: "Elegant engagement cake with edible flowers. Romantic! NEW!",
    imagens: ["images/novidades/nov8.jpg"],
    tamanhos: ["Grande"],
    sabores: ["Red Velvet", "Champagne"]
  },
  {
    id: "nov9",
    slug: "bolo-debutante",
    categoria: "novidades",
    nome_pt: "Bolo Debutante",
    nome_en: "Debutante Cake",
    preco: "720 MT",
    descricao_pt: "Bolo de 15 anos com decoração sofisticada. Inesquecível! NOVIDADE!",
    descricao_en: "15th birthday cake with sophisticated decoration. Unforgettable! NEW!",
    imagens: ["images/novidades/nov9.jpg"],
    tamanhos: ["Grande"],
    sabores: ["Baunilha", "Morango"]
  },
  {
    id: "nov10",
    slug: "bolo-casamento",
    categoria: "novidades",
    nome_pt: "Bolo de Casamento",
    nome_en: "Wedding Cake",
    preco: "1200 MT",
    descricao_pt: "Bolo de casamento em andares com flores naturais. Especial! NOVIDADE!",
    descricao_en: "Tiered wedding cake with natural flowers. Special! NEW!",
    imagens: ["images/novidades/nov10.jpg"],
    tamanhos: ["2 andares", "3 andares"],
    sabores: ["Baunilha", "Frutas Vermelhas"]
  },
  {
    id: "nov11",
    slug: "cupcake-sortido",
    categoria: "novidades",
    nome_pt: "Cupcake Sortido",
    nome_en: "Assorted Cupcakes",
    preco: "80 MT",
    descricao_pt: "Caixa com cupcakes variados. Perfeito para presentear! NOVIDADE!",
    descricao_en: "Box with assorted cupcakes. Perfect for gifting! NEW!",
    imagens: ["images/novidades/nov11.jpg"],
    tamanhos: ["Caixa c/ 4", "Caixa c/ 6", "Caixa c/ 12"],
    sabores: ["Sortido"]
  },
  {
    id: "nov12",
    slug: "cupcake-personalizado",
    categoria: "novidades",
    nome_pt: "Cupcake Personalizado",
    nome_en: "Custom Cupcake",
    preco: "45 MT",
    descricao_pt: "Cupcake decorado conforme tema escolhido. Único! NOVIDADE!",
    descricao_en: "Cupcake decorated according to chosen theme. Unique! NEW!",
    imagens: ["images/novidades/nov12.jpg"],
    tamanhos: ["Unidade"],
    sabores: ["Baunilha", "Chocolate", "Red Velvet"]
  },
  {
    id: "nov13",
    slug: "cake-pop",
    categoria: "novidades",
    nome_pt: "Cake Pop",
    nome_en: "Cake Pop",
    preco: "35 MT",
    descricao_pt: "Bolinho no palito coberto com chocolate. Divertido! NOVIDADE!",
    descricao_en: "Cake on a stick covered with chocolate. Fun! NEW!",
    imagens: ["images/novidades/nov13.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 6", "Caixa c/ 12"],
    sabores: ["Chocolate", "Baunilha", "Morango"]
  },
  {
    id: "nov14",
    slug: "pirulito-brownie",
    categoria: "novidades",
    nome_pt: "Pirulito de Brownie",
    nome_en: "Brownie Pop",
    preco: "40 MT",
    descricao_pt: "Brownie no palito coberto com chocolate. Criativo! NOVIDADE!",
    descricao_en: "Brownie on a stick covered with chocolate. Creative! NEW!",
    imagens: ["images/novidades/nov14.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 4"],
    sabores: ["Chocolate", "Oreo"]
  },
  {
    id: "nov15",
    slug: "docinhos-finos",
    categoria: "novidades",
    nome_pt: "Docinhos Finos",
    nome_en: "Fine Sweets",
    preco: "150 MT",
    descricao_pt: "Caixa com docinhos finos variados. Sofisticado! NOVIDADE!",
    descricao_en: "Box with assorted fine sweets. Sophisticated! NEW!",
    imagens: ["images/novidades/nov15.jpg"],
    tamanhos: ["Caixa c/ 12", "Caixa c/ 24"],
    sabores: ["Sortido"]
  },
  {
    id: "nov16",
    slug: "bem-casado",
    categoria: "novidades",
    nome_pt: "Bem-Casado",
    nome_en: "Bem-Casado",
    preco: "25 MT",
    descricao_pt: "Doce tradicional de casamento com doce de leite. Clássico! NOVIDADE!",
    descricao_en: "Traditional wedding sweet with dulce de leche. Classic! NEW!",
    imagens: ["images/novidades/nov16.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 10", "Caixa c/ 20"],
    sabores: ["Doce de Leite"]
  },
  {
    id: "nov17",
    slug: "mesa-doces",
    categoria: "novidades",
    nome_pt: "Mesa de Doces Completa",
    nome_en: "Complete Candy Table",
    preco: "3500 MT",
    descricao_pt: "Mesa de doces completa para eventos. Consulte-nos! NOVIDADE!",
    descricao_en: "Complete candy table for events. Contact us! NEW!",
    imagens: ["images/novidades/nov17.jpg"],
    tamanhos: ["50 pessoas", "100 pessoas"],
    sabores: ["Variado"]
  },
  {
    id: "nov18",
    slug: "kit-festa",
    categoria: "novidades",
    nome_pt: "Kit Festa",
    nome_en: "Party Kit",
    preco: "1200 MT",
    descricao_pt: "Kit festa com bolo, doces e salgados. Prático! NOVIDADE!",
    descricao_en: "Party kit with cake, sweets and snacks. Practical! NEW!",
    imagens: ["images/novidades/nov18.jpg"],
    tamanhos: ["10 pessoas", "20 pessoas", "30 pessoas"],
    sabores: ["Variado"]
  },
  {
    id: "nov19",
    slug: "kit-dia-maes",
    categoria: "novidades",
    nome_pt: "Kit Dia das Mães",
    nome_en: "Mother's Day Kit",
    preco: "450 MT",
    descricao_pt: "Kit especial para o Dia das Mães com bolo e doces. Carinhoso! NOVIDADE!",
    descricao_en: "Special kit for Mother's Day with cake and sweets. Caring! NEW!",
    imagens: ["images/novidades/nov19.jpg"],
    tamanhos: ["Kit P", "Kit M", "Kit G"],
    sabores: ["Variado"]
  },
  {
    id: "nov20",
    slug: "kit-dia-namorados",
    categoria: "novidades",
    nome_pt: "Kit Dia dos Namorados",
    nome_en: "Valentine's Day Kit",
    preco: "550 MT",
    descricao_pt: "Kit romântico para o Dia dos Namorados. Apaixonante! NOVIDADE!",
    descricao_en: "Romantic kit for Valentine's Day. Passionate! NEW!",
    imagens: ["images/novidades/nov20.jpg"],
    tamanhos: ["Kit P", "Kit M", "Kit G"],
    sabores: ["Chocolate", "Morango"]
  },
  {
    id: "nov21",
    slug: "kit-pascoa",
    categoria: "novidades",
    nome_pt: "Kit Páscoa",
    nome_en: "Easter Kit",
    preco: "480 MT",
    descricao_pt: "Kit de Páscoa com ovos de chocolate e doces. Delicioso! NOVIDADE!",
    descricao_en: "Easter kit with chocolate eggs and sweets. Delicious! NEW!",
    imagens: ["images/novidades/nov21.jpg"],
    tamanhos: ["Kit P", "Kit M", "Kit G"],
    sabores: ["Chocolate"]
  },
  {
    id: "nov22",
    slug: "kit-natal",
    categoria: "novidades",
    nome_pt: "Kit Natal",
    nome_en: "Christmas Kit",
    preco: "600 MT",
    descricao_pt: "Kit natalino com bolo especial e doces temáticos. Festivo! NOVIDADE!",
    descricao_en: "Christmas kit with special cake and themed sweets. Festive! NEW!",
    imagens: ["images/novidades/nov22.jpg"],
    tamanhos: ["Kit P", "Kit M", "Kit G"],
    sabores: ["Especiarias"]
  },
  {
    id: "nov23",
    slug: "ovo-pascoa-artesanal",
    categoria: "novidades",
    nome_pt: "Ovo de Páscoa Artesanal",
    nome_en: "Artisan Easter Egg",
    preco: "350 MT",
    descricao_pt: "Ovo de Páscoa artesanal recheado. Exclusivo! NOVIDADE!",
    descricao_en: "Artisan filled Easter egg. Exclusive! NEW!",
    imagens: ["images/novidades/nov23.jpg"],
    tamanhos: ["250g", "500g", "1kg"],
    sabores: ["Chocolate", "Nutella", "Oreo"]
  },
  {
    id: "nov24",
    slug: "panetone-artesanal",
    categoria: "novidades",
    nome_pt: "Panetone Artesanal",
    nome_en: "Artisan Panettone",
    preco: "280 MT",
    descricao_pt: "Panetone artesanal com frutas cristalizadas. Tradição! NOVIDADE!",
    descricao_en: "Artisan panettone with crystallized fruits. Tradition! NEW!",
    imagens: ["images/novidades/nov24.jpg"],
    tamanhos: ["500g", "750g", "1kg"],
    sabores: ["Frutas", "Chocolate"]
  },
  {
    id: "nov25",
    slug: "chocotone",
    categoria: "novidades",
    nome_pt: "Chocotone",
    nome_en: "Chocottone",
    preco: "300 MT",
    descricao_pt: "Panetone de chocolate com gotas de chocolate. Irresistível! NOVIDADE!",
    descricao_en: "Chocolate panettone with chocolate chips. Irresistible! NEW!",
    imagens: ["images/novidades/nov25.jpg"],
    tamanhos: ["500g", "750g", "1kg"],
    sabores: ["Chocolate"]
  },
  {
    id: "nov26",
    slug: "bolo-pote",
    categoria: "novidades",
    nome_pt: "Bolo de Pote",
    nome_en: "Jar Cake",
    preco: "150 MT",
    descricao_pt: "Bolo em camadas no pote, prático e delicioso. NOVIDADE!",
    descricao_en: "Layered cake in a jar, practical and delicious. NEW!",
    imagens: ["images/novidades/nov26.jpg"],
    tamanhos: ["Pote 250ml", "Pote 500ml"],
    sabores: ["Chocolate", "Morango", "Ninho"]
  },
  {
    id: "nov27",
    slug: "taca-sobremesa",
    categoria: "novidades",
    nome_pt: "Taça de Sobremesa",
    nome_en: "Dessert Cup",
    preco: "180 MT",
    descricao_pt: "Taça com camadas de bolo, creme e frutas. Elegante! NOVIDADE!",
    descricao_en: "Cup with layers of cake, cream and fruits. Elegant! NEW!",
    imagens: ["images/novidades/nov27.jpg"],
    tamanhos: ["Individual", "Família"],
    sabores: ["Morango", "Maracujá", "Chocolate"]
  },
  {
    id: "nov28",
    slug: "barra-chocolate-recheada",
    categoria: "novidades",
    nome_pt: "Barra de Chocolate Recheada",
    nome_en: "Filled Chocolate Bar",
    preco: "200 MT",
    descricao_pt: "Barra de chocolate artesanal recheada. Criativa! NOVIDADE!",
    descricao_en: "Artisan filled chocolate bar. Creative! NEW!",
    imagens: ["images/novidades/nov28.jpg"],
    tamanhos: ["100g", "200g"],
    sabores: ["Nutella", "Oreo", "Brigadeiro"]
  },
  {
    id: "nov29",
    slug: "cone-trufado",
    categoria: "novidades",
    nome_pt: "Cone Trufado",
    nome_en: "Truffled Cone",
    preco: "80 MT",
    descricao_pt: "Cone de chocolate recheado com brigadeiro. Divertido! NOVIDADE!",
    descricao_en: "Chocolate cone filled with brigadeiro. Fun! NEW!",
    imagens: ["images/novidades/nov29.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 4"],
    sabores: ["Chocolate", "Ninho"]
  },
  {
    id: "nov30",
    slug: "bomba-chocolate",
    categoria: "novidades",
    nome_pt: "Bomba de Chocolate",
    nome_en: "Chocolate Bomb",
    preco: "120 MT",
    descricao_pt: "Bomba de chocolate que derrete no leite quente. Mágica! NOVIDADE!",
    descricao_en: "Chocolate bomb that melts in hot milk. Magical! NEW!",
    imagens: ["images/novidades/nov30.jpg"],
    tamanhos: ["Unidade", "Kit c/ 3"],
    sabores: ["Chocolate", "Marshmallow"]
  },
  {
    id: "nov31",
    slug: "pudim-pote",
    categoria: "novidades",
    nome_pt: "Pudim no Pote",
    nome_en: "Jar Pudding",
    preco: "100 MT",
    descricao_pt: "Pudim de leite no pote, prático para levar. NOVIDADE!",
    descricao_en: "Milk pudding in a jar, practical to go. NEW!",
    imagens: ["images/novidades/nov31.jpg"],
    tamanhos: ["Pote 200ml", "Pote 400ml"],
    sabores: ["Leite", "Chocolate", "Coco"]
  },
  {
    id: "nov32",
    slug: "mousse-pote",
    categoria: "novidades",
    nome_pt: "Mousse no Pote",
    nome_en: "Jar Mousse",
    preco: "90 MT",
    descricao_pt: "Mousse no pote, vários sabores disponíveis. NOVIDADE!",
    descricao_en: "Mousse in a jar, various flavors available. NEW!",
    imagens: ["images/novidades/nov32.jpg"],
    tamanhos: ["Pote 150ml", "Pote 300ml"],
    sabores: ["Maracujá", "Chocolate", "Morango"]
  },
  {
    id: "nov33",
    slug: "brigadeiro-gourmet",
    categoria: "novidades",
    nome_pt: "Brigadeiro Gourmet",
    nome_en: "Gourmet Brigadeiro",
    preco: "35 MT",
    descricao_pt: "Brigadeiro gourmet em sabores especiais. Sofisticado! NOVIDADE!",
    descricao_en: "Gourmet brigadeiro in special flavors. Sophisticated! NEW!",
    imagens: ["images/novidades/nov33.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 4", "Caixa c/ 8"],
    sabores: ["Café", "Pistache", "Avelã"]
  },
  {
    id: "nov34",
    slug: "trufa-especial",
    categoria: "novidades",
    nome_pt: "Trufa Especial",
    nome_en: "Special Truffle",
    preco: "50 MT",
    descricao_pt: "Trufa em sabores exclusivos. Premium! NOVIDADE!",
    descricao_en: "Truffle in exclusive flavors. Premium! NEW!",
    imagens: ["images/novidades/nov34.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 4"],
    sabores: ["Champagne", "Cereja", "Licor"]
  },
  {
    id: "nov35",
    slug: "bombom-artesanal",
    categoria: "novidades",
    nome_pt: "Bombom Artesanal",
    nome_en: "Artisan Chocolate",
    preco: "45 MT",
    descricao_pt: "Bombom artesanal com recheios especiais. Delicado! NOVIDADE!",
    descricao_en: "Artisan chocolate with special fillings. Delicate! NEW!",
    imagens: ["images/novidades/nov35.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 6", "Caixa c/ 12"],
    sabores: ["Caramelo", "Frutas", "Licor"]
  },
  {
    id: "nov36",
    slug: "pao-mel-recheado",
    categoria: "novidades",
    nome_pt: "Pão de Mel Recheado Especial",
    nome_en: "Special Filled Honey Bread",
    preco: "55 MT",
    descricao_pt: "Pão de mel com recheios especiais. Irresistível! NOVIDADE!",
    descricao_en: "Honey bread with special fillings. Irresistible! NEW!",
    imagens: ["images/novidades/nov36.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 3", "Caixa c/ 6"],
    sabores: ["Doce de Leite", "Nutella", "Brigadeiro"]
  },
  {
    id: "nov37",
    slug: "alfajor-premium",
    categoria: "novidades",
    nome_pt: "Alfajor Premium",
    nome_en: "Premium Alfajor",
    preco: "60 MT",
    descricao_pt: "Alfajor premium com recheio especial. Sofisticado! NOVIDADE!",
    descricao_en: "Premium alfajor with special filling. Sophisticated! NEW!",
    imagens: ["images/novidades/nov37.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 3"],
    sabores: ["Doce de Leite", "Nutella"]
  },
  {
    id: "nov38",
    slug: "cookie-gourmet",
    categoria: "novidades",
    nome_pt: "Cookie Gourmet",
    nome_en: "Gourmet Cookie",
    preco: "50 MT",
    descricao_pt: "Cookie gourmet com ingredientes premium. Delicioso! NOVIDADE!",
    descricao_en: "Gourmet cookie with premium ingredients. Delicious! NEW!",
    imagens: ["images/novidades/nov38.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 3"],
    sabores: ["Chocolate Belga", "Macadâmia"]
  },
  {
    id: "nov39",
    slug: "macaron-premium",
    categoria: "novidades",
    nome_pt: "Macaron Premium",
    nome_en: "Premium Macaron",
    preco: "150 MT",
    descricao_pt: "Macaron francês em sabores premium. Elegante! NOVIDADE!",
    descricao_en: "French macaron in premium flavors. Elegant! NEW!",
    imagens: ["images/novidades/nov39.jpg"],
    tamanhos: ["Unidade", "Caixa c/ 3"],
    sabores: ["Pistache", "Framboesa", "Lavanda"]
  },
  {
    id: "nov40",
    slug: "cheesecake-pote",
    categoria: "novidades",
    nome_pt: "Cheesecake no Pote",
    nome_en: "Jar Cheesecake",
    preco: "160 MT",
    descricao_pt: "Cheesecake no pote com calda de frutas. Prático! NOVIDADE!",
    descricao_en: "Cheesecake in a jar with fruit sauce. Practical! NEW!",
    imagens: ["images/novidades/nov40.jpg"],
    tamanhos: ["Pote 200ml", "Pote 400ml"],
    sabores: ["Morango", "Frutas Vermelhas"]
  },
  {
    id: "nov41",
    slug: "tiramisu-pote",
    categoria: "novidades",
    nome_pt: "Tiramisù no Pote",
    nome_en: "Jar Tiramisu",
    preco: "180 MT",
    descricao_pt: "Tiramisù autêntico no pote. Italiano! NOVIDADE!",
    descricao_en: "Authentic tiramisu in a jar. Italian! NEW!",
    imagens: ["images/novidades/nov41.jpg"],
    tamanhos: ["Pote 200ml", "Pote 400ml"],
    sabores: ["Café", "Amaretto"]
  },
  {
    id: "nov42",
    slug: "pave-pote",
    categoria: "novidades",
    nome_pt: "Pavê no Pote",
    nome_en: "Jar Pavê",
    preco: "140 MT",
    descricao_pt: "Pavê no pote, vários sabores. Clássico! NOVIDADE!",
    descricao_en: "Pavê in a jar, various flavors. Classic! NEW!",
    imagens: ["images/novidades/nov42.jpg"],
    tamanhos: ["Pote 200ml", "Pote 400ml"],
    sabores: ["Chocolate", "Limão"]
  },
  {
    id: "nov43",
    slug: "sorvete-bolo",
    categoria: "novidades",
    nome_pt: "Sorvete de Bolo",
    nome_en: "Cake Ice Cream",
    preco: "200 MT",
    descricao_pt: "Sorvete com pedaços de bolo. Refrescante! NOVIDADE!",
    descricao_en: "Ice cream with cake pieces. Refreshing! NEW!",
    imagens: ["images/novidades/nov43.jpg"],
    tamanhos: ["Pote 500ml", "Pote 1L"],
    sabores: ["Chocolate", "Baunilha", "Morango"]
  },
  {
    id: "nov44",
    slug: "gelatina-artistica",
    categoria: "novidades",
    nome_pt: "Gelatina Artística",
    nome_en: "Artistic Gelatin",
    preco: "250 MT",
    descricao_pt: "Gelatina decorada artisticamente. Linda! NOVIDADE!",
    descricao_en: "Artistically decorated gelatin. Beautiful! NEW!",
    imagens: ["images/novidades/nov44.jpg"],
    tamanhos: ["Individual", "Família"],
    sabores: ["Frutas"]
  },
  {
    id: "nov45",
    slug: "mini-bolo",
    categoria: "novidades",
    nome_pt: "Mini Bolo",
    nome_en: "Mini Cake",
    preco: "180 MT",
    descricao_pt: "Mini bolo individual, perfeito para presente. NOVIDADE!",
    descricao_en: "Individual mini cake, perfect for gifting. NEW!",
    imagens: ["images/novidades/nov45.jpg"],
    tamanhos: ["Individual"],
    sabores: ["Chocolate", "Baunilha", "Red Velvet"]
  },
  {
    id: "nov46",
    slug: "mini-torta",
    categoria: "novidades",
    nome_pt: "Mini Torta",
    nome_en: "Mini Pie",
    preco: "160 MT",
    descricao_pt: "Mini torta individual, vários sabores. NOVIDADE!",
    descricao_en: "Individual mini pie, various flavors. NEW!",
    imagens: ["images/novidades/nov46.jpg"],
    tamanhos: ["Individual"],
    sabores: ["Limão", "Morango", "Chocolate"]
  },
  {
    id: "nov47",
    slug: "mini-pudim",
    categoria: "novidades",
    nome_pt: "Mini Pudim",
    nome_en: "Mini Pudding",
    preco: "80 MT",
    descricao_pt: "Mini pudim individual, perfeito para festas. NOVIDADE!",
    descricao_en: "Individual mini pudding, perfect for parties. NEW!",
    imagens: ["images/novidades/nov47.jpg"],
    tamanhos: ["Individual"],
    sabores: ["Leite", "Chocolate", "Coco"]
  },
  {
    id: "nov48",
    slug: "kit-brigadeiro",
    categoria: "novidades",
    nome_pt: "Kit Brigadeiro",
    nome_en: "Brigadeiro Kit",
    preco: "350 MT",
    descricao_pt: "Kit para fazer brigadeiro em casa. Divertido! NOVIDADE!",
    descricao_en: "Kit to make brigadeiro at home. Fun! NEW!",
    imagens: ["images/novidades/nov48.jpg"],
    tamanhos: ["Kit Completo"],
    sabores: ["Chocolate"]
  },
  {
    id: "nov49",
    slug: "kit-confeiteiro",
    categoria: "novidades",
    nome_pt: "Kit Confeiteiro",
    nome_en: "Baker Kit",
    preco: "400 MT",
    descricao_pt: "Kit com utensílios e ingredientes para confeitar. NOVIDADE!",
    descricao_en: "Kit with utensils and ingredients for baking. NEW!",
    imagens: ["images/novidades/nov49.jpg"],
    tamanhos: ["Kit Completo"],
    sabores: ["Variado"]
  },
  {
    id: "nov50",
    slug: "vale-presente",
    categoria: "novidades",
    nome_pt: "Vale-Presente",
    nome_en: "Gift Voucher",
    preco: "500 MT",
    descricao_pt: "Vale-presente para usar em qualquer produto. Ideal para presentear! NOVIDADE!",
    descricao_en: "Gift voucher to use on any product. Ideal for gifting! NEW!",
    imagens: ["images/novidades/nov50.jpg"],
    tamanhos: ["500 MT", "1000 MT", "2000 MT"],
    sabores: ["-"]
  }
];

// Exportar para uso em outros arquivos
if (typeof module !== 'undefined' && module.exports) {
  module.exports = PRODUTOS;
}
